name: Maven CI/CD Pipeline

# Quando este pipeline será executado
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Jobs do pipeline
jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root_pass
          MYSQL_DATABASE: app
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    # Passos que o job irá executar
    steps:
    - name: Checkout código-fonte
      uses: actions/checkout@v2

    - name: Configurar JDK 21
      uses: actions/setup-java@v2
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Build com Maven
      run: mvn clean install -DskipTests
      env:
        SPRING_PROFILES_ACTIVE: dev   # Ou "prod" para produção


  docker:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout código-fonte
      uses: actions/checkout@v2

    - name: Configurar JDK 21
      uses: actions/setup-java@v2
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Build Docker Image
      run: docker build -t meuapp:latest .

    - name: Testar Docker Image
      run: docker run --rm meuapp:latest

